### ISSUE TITLE
Bot

### ISSUE THREAD

**Issue by fdr42** [w0dm4n/BotVote-RPG-PARADIZE#1]
Salut ! 
Je n'arrive pas a faire tourner ton bot, aucun vote ne s'ajoute.
Penses tu qu'il est encoe valable?
Merci

**Comment by w0dm4n** [comment]
Salut, non je ne pense pas qu'il fonctionne par contre il peux servir de base pour en faire un nouveau

**Comment by fdr42** [comment]
Est t'il possible de profiter de ton expérience?
J'ai essayé d'en créer un nouveau, en récupérant les cookies, les parametres post mais cela ne fonctionne pas. tout semble pourtant bon coté code, et rpg a le meme comportement que quand on vote vraiment.
Comment as tu trouvé les parametres attendus par rpg quand tu as créé le tient?

**Comment by w0dm4n** [comment]
j'ai simplement imiter le même comportement qu'un navigateur web qui irait naviguer sur rpg-paradize et initier un vote, et pour les paramètres attendus juste en regardant les datas http des requests en le faisant de manière classique

**Comment by fdr42** [comment]
Bonjour,
Mes recherches avancent mais ne donnent rien, j'ai l'impression que l'on ne
peut pas utiliser n'importe quel proxy,
Sais tu quels proxys sont viables pour cette opération ?
Merci

**Comment by w0dm4n** [comment]
Des socks 5 legit de préférence
